# Generated by Django 3.2.6 on 2021-08-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='name',
            field=models.CharField(default='sample', max_length=20),
            preserve_default=False,
        ),
    ]
