# Generated by Django 3.2.6 on 2021-08-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_useraddress_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='contact_mobile',
            field=models.CharField(default='s', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='contact_name',
            field=models.CharField(default='s', max_length=30),
            preserve_default=False,
        ),
    ]
