# Generated by Django 3.2.6 on 2021-08-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_useraddress_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name_plural': 'User Addresses'},
        ),
    ]
