# Generated by Django 3.2.6 on 2021-08-27 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_value', models.CharField(max_length=50)),
                ('total_codes', models.IntegerField(default=0)),
                ('code_1', models.CharField(blank=True, max_length=50, null=True)),
                ('code_2', models.CharField(blank=True, max_length=50, null=True)),
                ('code_3', models.CharField(blank=True, max_length=50, null=True)),
                ('code_4', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('attribute_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.attributemaster')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AtV_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AtV_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Attribute Values',
            },
        ),
    ]
