# Generated by Django 3.2.6 on 2021-08-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_attributevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='color_abbr',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
