# Generated by Django 3.2.6 on 2021-08-28 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_attributevalue_color_abbr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributemaster',
            old_name='updated_by',
            new_name='modified_by',
        ),
        migrations.RenameField(
            model_name='attributevalue',
            old_name='updated_by',
            new_name='modified_by',
        ),
        migrations.CreateModel(
            name='PrimaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], default='Men', max_length=10)),
                ('display_order', models.IntegerField(default=1)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pCat_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pCat_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Primary Categories',
            },
        ),
    ]
