# Generated by Django 3.2.6 on 2021-08-31 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0012_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_sku', models.CharField(max_length=20)),
                ('user_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('user_review', models.TextField(max_length=600)),
                ('like', models.IntegerField()),
                ('dislike', models.IntegerField()),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_modifier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
