# Generated by Django 3.2.6 on 2021-08-31 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='like',
        ),
    ]
