# Generated by Django 3.2.6 on 2021-09-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_reviewreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.FloatField(default=18),
            preserve_default=False,
        ),
    ]
