# Generated by Django 3.2.6 on 2021-09-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderactivity',
            options={'verbose_name_plural': 'Order Activities'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='orderrefund',
            options={'verbose_name_plural': 'Order Refunds'},
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
