# Generated by Django 3.2.6 on 2021-09-26 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210908_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('PL', 'Placed'), ('CU', 'Cancelled By User'), ('CN', 'Cancelled'), ('PK', 'Packed'), ('TN', 'In Transit'), ('DV', 'Delivered'), ('RI', 'Return Initiated'), ('RC', 'Return Completed')], max_length=2),
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp_payment_id', models.CharField(max_length=200)),
                ('rp_order_id', models.CharField(max_length=200)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'verbose_name_plural': 'Order Payments',
            },
        ),
    ]
