# Generated by Django 3.2.6 on 2021-09-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210926_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='success',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
