# Generated by Django 3.2.6 on 2021-09-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderpayment_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('PL', 'Placed'), ('CU', 'Cancelled By User'), ('CN', 'Cancelled'), ('PK', 'Packed'), ('TN', 'In Transit'), ('DV', 'Delivered'), ('RI', 'Return Initiated'), ('RC', 'Return Completed'), ('FL', 'Failed')], max_length=2),
        ),
    ]
